### ISSUE TITLE
Crafting Recipe?

### ISSUE THREAD

**Issue by WildFyr16** [PunJarrr/MoreBricks#4]
I have been looking far and wide trying to figure out how to craft these. The stonecutter, crafting table, and JEI are not helping me. What is the crafting recipe for these blocks? There is no documentation, and the description is sub par.

**Comment by PunJarrr** [comment]
Ok I'll fix that bug, thank you for your feedback!

**Comment by PunJarrr** [comment]
And I'll make a description and documentation better.

**Comment by PunJarrr** [comment]
I fixed those issues!

**Comment by PunJarrr** [comment]
I fixed those issues!

**Comment by WildFyr16** [comment]
Great! Thank you so much can't wait to use these blocks in my builds!

**Comment by PunJarrr** [comment]
Np
